# load zgen
# source "${HOME}/.zgen/zgen.zsh"
# 
# if ! zgen saved; then
#   zgen prezto
# fi

#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...

source "$HOME/.brewsn.zshrc"

export GROOVY_HOME=/usr/local/opt/groovy/libexec
export JAVA_HOME=/Library/Java/JavaVirtualMachines/jdk1.8.0_121.jdk/Contents/Home

export PATH=$PATH:$HOME/bin

[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh

fpath=(/usr/local/share/zsh-completions $fpath)

# ag extensions
alias agp='ag --pager '\''less -r'\'''
function agx { local term=$1; shift; ag -l --xml "$term" | xargs ag -H --filename "<name>|$term" "$@"; }

# nvm
export NVM_DIR="$HOME/.nvm"
[ -s "/usr/local/opt/nvm/nvm.sh" ] && source "/usr/local/opt/nvm/nvm.sh"  # This loads nvm

# python virtualenv
VIRTUALENVWRAPPER_PYTHON=$(which python3)
export WORKON_HOME=~/.virtualenvs
[ -f /usr/local/bin/virtualenvwrapper.sh ] && source /usr/local/bin/virtualenvwrapper.sh

# [ -s "/usr/local/opt/nvm/etc/bash_completion" ] && . "/usr/local/opt/nvm/etc/bash_completion"  # This loads nvm bash_completion

# lazynvm() {
#   unset -f nvm node npm
#   export NVM_DIR=~/.nvm
#   [ -s "$NVM_DIR/nvm.sh" ] && . "$NVM_DIR/nvm.sh"  # This loads nvm
# }
# 
# nvm() {
#   lazynvm 
#   nvm $@
# }
# 
# node() {
#   lazynvm
#   node $@
# }
# 
# npm() {
#   lazynvm
#   npm $@
# }

